circly/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^submitname/$', views.submitname, name='submitname'),
    url(r'^flow/$', views.flow, name='flow'),
    url(r'^invite/(?P<invite_hash>[0-9a-fA-F]+:[0-9a-fA-F]+)$', views.invite, name='invite'),
    url(r'^submitprofile/$', views.submitprofile, name='submitprofile'),
    url(r'^network/$', views.network, name='network'),
    url(r'^submitcircle/$', views.submitcircle, name='submitcircle'),
    url(r'^dashboard/(?P<owner_hash>[0-9a-fA-F]+:[0-9a-fA-F]+)$', views.dashboard, name='dashboard'),
    url(r'^thankyou/$', views.thankyou, name='thankyou'),
    url(r'^checkmeout/$', views.checkmeout, name='checkmeout'),
]

event_meet/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = [url(r'', include('circly.urls', namespace="connect")),
               url(r'^admin/', include(admin.site.urls)),
]

circly/models.py
import uuid
from django.db.models import Model
from django.db.models import CharField, DateTimeField, ForeignKey, BooleanField
from django.db.models import URLField, SmallIntegerField, UUIDField
from django.utils import timezone


class Event(Model):
    event_id = CharField(max_length=50)
    event_name = CharField(max_length=200)
    event_date = DateTimeField('date of event')

    def __unicode__(self):
        return self.event_name


class Attendee(Model):
    event = ForeignKey(Event)
    attendee_id = CharField(max_length=50)
    attendee_email = CharField(max_length=200)
    attendee_name = CharField(max_length=100)
    checked_in = BooleanField(default=False)

    def __unicode__(self):
        return self.attendee_name


class Circle(Model):
    circle_name = CharField(max_length=100)
    circle_created_date = DateTimeField('circle created on')
    circle_reminders_refreshed_on_date = DateTimeField('reminders refreshed on', null=True, blank=True)
    circle_short_url = URLField(null=True, blank=True)

    def circle_owner_name(self):
        circle_owner = self.member_set.filter(circle_owner=True)
        name_str = circle_owner[0].member_name

        return name_str


    def __unicode__(self):
        return self.circle_name


class Member(Model):
    from choices_member import UNDER_20, BTWN_20_29, BTWN_30_39, BTWN_40_44, BTWN_45_49, BTWN_50_59, OVER_60
    from choices_member import FEMALE, MALE
    from choices_member import WHITE, BLACK, HISPANIC, ASIAN, OTHER
    from choices_member import YES, NO
    from choices_member import BMI_UNDER, BMI_OVER
    from choices_member import AGE_RANGE_CHOICES, SEX_CHOICES, ETHNICITY_CHOICES, DRINK_CHOICES, SMOKE_CHOICES, EXERCISE_CHOICES, BMI_CHOICES, RELATIVE_CHOICES

    circle = ForeignKey(Circle)
    circle_owner = BooleanField(default=False)
    member_name = CharField(max_length=100)
    member_created_date = DateTimeField('member created on', null=True, blank=True)
    member_email = CharField(max_length=200, null=True, blank=True)
    member_phone = CharField(max_length=25, null=True, blank=True)

    age_range = CharField(max_length=5,
                          choices=AGE_RANGE_CHOICES,
                          default=BTWN_20_29)

    sex_range = CharField(max_length=2,
                          choices=SEX_CHOICES,
                          default=FEMALE)

    ethnicity_range = CharField(max_length=3,
                                choices=ETHNICITY_CHOICES,
                                default=WHITE)

    bmi_range = CharField(max_length=3,
                          choices=BMI_CHOICES,
                          default=BMI_UNDER)

    smoker = BooleanField(default=False)
    drinker = BooleanField(default=False)
    exercises = BooleanField(default=True)

    cancer_family = SmallIntegerField(default=0)

    member_profile_entered_date = DateTimeField('profile entered on', null=True, blank=True)


    def risk(self):
        female_risk_percentage = {UNDER_20: 0.0000,
                                  BTWN_20_29: 0.0006,
                                  BTWN_30_39: 0.0044,
                                  BTWN_40_44: 0.0145,
                                  BTWN_45_49: 0.0145,
                                  BTWN_50_59: 0.0233,
                                  OVER_60: 0.0345,
                                 }

        male_risk_percentage = 0.0010

        return


    def add_reminders(self):
        return


    def __unicode__(self):
        return self.member_name


class Invitation(Model):
    id = UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    member = ForeignKey(Member)
    invite_code = CharField(max_length=300, null=True, blank=True)
    invite_short_url = URLField(null=True, blank=True)
    invite_created_date = DateTimeField('invite created on')
    invite_send_date = DateTimeField('send invite on', null=True, blank=True)
    invite_sent_on_date = DateTimeField('invite sent on', null=True, blank=True)
    member_joined_on_date = DateTimeField('member joined on', null=True, blank=True)


    def __unicode__(self):
        return unicode(self.id)


class Reminder(Model):
    id = UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    member = ForeignKey(Member)
    reminder_subject = CharField(max_length=65)
    reminder_message = CharField(max_length=150)
    reminder_created_date = DateTimeField('reminder created on')
    reminder_send_date = DateTimeField('send reminder on', null=True, blank=True)
    reminder_sent_on_date = DateTimeField('reminder sent on', null=True, blank=True)
    member_reminded_on_date = DateTimeField('member reminded on', null=True, blank=True)


    def is_an_email(self):
        if (self.member.member_email):
            return True

        return False


    def is_an_SMS(self):
        if (self.member.member_phone):
            return True

        return False


    def __unicode__(self):
        return unicode(self.id)

circly/forms.py
from django import forms
from choices_member import *


class NameForm(forms.Form):
    name = forms.CharField(max_length=100, required=True)
    contact_info = forms.CharField(max_length=200, required=True)


class FlowForm(forms.Form):
    chromosome = forms.ChoiceField(choices=SEX_CHOICES, widget=forms.Select, required=True)
    age = forms.ChoiceField(choices=AGE_RANGE_CHOICES, widget=forms.Select, required=True)
    ethnicity = forms.ChoiceField(choices=ETHNICITY_CHOICES, label="ethnicity", widget=forms.Select, required=True)
    drink = forms.ChoiceField(choices=DRINK_CHOICES, widget=forms.Select, required=True)
    smoke = forms.ChoiceField(choices=SMOKE_CHOICES, widget=forms.Select, required=True)
    exercise = forms.ChoiceField(choices=EXERCISE_CHOICES, widget=forms.Select, required=True)
    bmi = forms.ChoiceField(choices=BMI_CHOICES, widget=forms.Select, required=True)
    relatives = forms.ChoiceField(choices=RELATIVE_CHOICES, widget=forms.Select, required=True)
    invite = forms.BooleanField(widget=forms.HiddenInput(), required=False)

circly/views.py
import datetime
from django import forms

from django.conf import settings
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect, HttpResponse, Http404
from django.shortcuts import get_object_or_404, render, redirect
from django.template import RequestContext, loader
from django.utils import timezone
from django.utils.safestring import mark_safe
from django.utils.html import format_html
from django.views import generic

from choices_member import *
from forms import *
from helpers import clear_member_and_circle, set_member_and_circle, get_current_member, get_current_circle
from helpers import check_invite, check_owner, hash_code
from helpers import is_phone, is_email
from helpers import random_bitly

import phonenumbers

from models import Circle, Member, Reminder, Invitation


def index(request):
    clear_member_and_circle(request)

    context = {}
    return render(request, "circly/index.html", context)


def submitname(request):
    first_name = request.POST.get("first_name", None)
    contact_info = request.POST.get("contact_info", None)

    context = {}
    custom_errors = ""

    if (first_name):
        context["first_name"] = first_name

        if (contact_info):
            context["contact_info"] = contact_info

            # Create a circle
            new_circle = Circle(circle_name=first_name + "'s circle",
                                circle_created_date=timezone.now(), )
            new_circle.save()

            # Create our new member
            new_member = Member(circle=new_circle,
                                circle_owner=True,
                                member_name=first_name,
                                member_created_date=timezone.now(), )

            # Check to see if current contact info is valid phone or email
            if is_phone(contact_info):
                new_phone = phonenumbers.parse(contact_info, "US")
                new_phone = phonenumbers.format_number(new_phone, phonenumbers.PhoneNumberFormat.E164)

                new_member.member_phone = new_phone

            if is_email(contact_info):
                new_member.member_email = contact_info

            if not is_phone(contact_info) and not is_email(contact_info):
                # Bad data error
                custom_errors += "<li>contact info must be either a valid phone number OR email</li>"

            new_member.save()

            set_member_and_circle(request, new_circle, new_member)
        else:
            # Missing contact data error
            custom_errors += "<li>name is present but contact info is missing</li>"
    else:
        # Missing name data error
        custom_errors += "<li>"

        if (contact_info):
            context["contact_info"] = contact_info
            custom_errors += "contact info is present but "

        custom_errors += "name is missing</li>"

    if custom_errors != "":
        custom_errors = format_html("<p><ul>{}</ul></p>",
                                    mark_safe(custom_errors))

        # If there are any errors, kick out and display them
        context["custom_errors"] = custom_errors
        context["anchor"] = "signup"
        return render(request, "circly/index.html", context)

    return HttpResponseRedirect(reverse("connect:flow", 
                                        kwargs={}))


def flow(request):
    new_member = get_current_member(request)

    if request.method == "POST":
        profile_form = FlowForm(request.POST, initial={"invite": False})

        if profile_form.is_valid():
            return HttpResponseRedirect(reverse("connect:submitprofile", 
                                        kwargs={}))
    else:
        profile_form = FlowForm(auto_id="f_%s", initial={"invite": False})

    context = {"member":new_member, "form": profile_form, }
    return render(request, "circly/flow.html", context)


def invite(request, invite_hash):
    if request.method == "POST":
        new_member = get_current_member(request)

        profile_form = FlowForm(request.POST, initial={"invite": True})

        if profile_form.is_valid():
            return HttpResponseRedirect(reverse("connect:submitprofile", 
                                        kwargs={}))
    else:
        invite_member_id = check_invite(invite_hash)

        if invite_member_id:
            new_member = get_object_or_404(Member, pk=invite_member_id)
            new_circle = get_object_or_404(Circle, pk=new_member.circle.id)

            set_member_and_circle(request, new_circle, new_member)

            profile_form = FlowForm(auto_id="f_%s", initial={"invite": True})
        else:
            raise Http404

    context = {"member":new_member, "form": profile_form, }
    return render(request, "circly/flow.html", context)


def submitprofile(request):
    invite = request.POST.get("invite", None)
    new_member = get_current_member(request)

    chromosome = request.POST.get("chromosome", "")
    age = request.POST.get("age", "")
    ethnicity = request.POST.get("ethnicity", "")
    drink = request.POST.get("drink", "")
    smoke = request.POST.get("smoke", "")
    exercise = request.POST.get("exercise", "")
    bmi = request.POST.get("bmi", "")
    relatives = int(request.POST.get("relatives", 0))

    new_member.age_range = age
    new_member.sex_range = chromosome
    new_member.ethnicity_range = ethnicity
    new_member.bmi_range = bmi
    new_member.cancer_family = relatives

    if (drink == YES):
        new_member.drinker = True
    else:
        new_member.drinker = False

    if (smoke == YES):
        new_member.smoker = True
    else:
        new_member.smoker = False

    if (exercise == YES):
        new_member.exercises = True
    else:
        new_member.exercises = False

    new_member.member_profile_entered_date = timezone.now()

    new_member.save()

    if invite == "True":
        submit_url = "connect:thankyou"
    else:
        submit_url = "connect:network"

    return HttpResponseRedirect(reverse(submit_url,
                                        kwargs={}))


def network(request):
    new_member = get_current_member(request)

    context = {"member":new_member, "num_range_str":settings.CONTACT_RANGE_STR, "custom_errors":""}
    return render(request, "circly/network.html", context)


def submitcircle(request):
    new_member = get_current_member(request)
    new_circle = get_current_circle(request)

    count = 2
    posted_members = {}

    custom_errors = ""

    while count <= settings.CIRCLE_MAX_SIZE:
        member_contact = {}

        current_name = request.POST.get("name_" + str(count), None)
        current_contact = request.POST.get("contact_" + str(count), None)

        if (current_name):
            if (current_contact):
                # Check to see if current contact info is valid phone or email
                if is_phone(current_contact):
                    member_contact["contact_type"] = "phone"

                if is_email(current_contact):
                    member_contact["contact_type"] = "email"

                if not is_phone(current_contact) and not is_email(current_contact):
                    # Bad data error
                    custom_errors += "<li>contact_" + str(count) + " must be either a valid phone number OR email</li>"

                member_contact["contact_info"] = current_contact

                posted_members[current_name] = member_contact
            else:
                # Missing contact data error
                custom_errors += "<li>name_" + str(count) + " is present but contact_" + str(count) + " is missing</li>"
        else:
            if len(posted_members) < (settings.CIRCLE_MIN_SIZE - 1):
                # Missing name data error
                custom_errors += "<li>name_" + str(count) + " is missing</li>"

        count += 1

    # Check to see if we have minimum more members added
    if len(posted_members) < (settings.CIRCLE_MIN_SIZE - 1):
        custom_errors += "<li>You need at least " + str(settings.CIRCLE_MIN_SIZE) + " members (including yourself) in your circle</li>"

    if custom_errors != "":
        custom_errors = format_html("<p><ul>{}</ul></p>",
                                    mark_safe(custom_errors))

        # If there are any errors, kick out and display them
        context = {"member":new_member, "num_range_str":settings.CONTACT_RANGE_STR, "custom_errors":custom_errors, }
        return render(request, "circly/network.html", context)

    for each_member in posted_members.keys():
        # Create new members and add to the circle
        if (posted_members[each_member]["contact_type"] == "email"):
            next_member = Member(circle=new_circle,
                                 circle_owner=False,
                                 member_name=each_member,
                                 member_email=posted_members[each_member]["contact_info"],
                                 member_created_date=timezone.now(), )
        elif (posted_members[each_member]["contact_type"] == "phone"):
            new_phone = phonenumbers.parse(posted_members[each_member]["contact_info"], "US")
            new_phone = phonenumbers.format_number(new_phone, phonenumbers.PhoneNumberFormat.E164)

            next_member = Member(circle=new_circle,
                                 circle_owner=False,
                                 member_name=each_member,
                                 member_phone=new_phone,
                                 member_created_date=timezone.now(), )

        next_member.save()

        # Create invite code with short link for profile sign up
        invite_code = hash_code(posted_members[each_member]["contact_info"])

        invite_url = "http://www.circly.org/invite/" + invite_code
        new_short_url = random_bitly(invite_url)

        invite = Invitation(member=next_member,
                            invite_code=invite_code, 
                            invite_short_url=new_short_url, 

event_meet/templates/circly/base.html
{% load staticfiles %}<!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]> <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]> <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  <title>{% block title %}{% endblock %}</title>
  <meta name="description" content="">

  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
{% block blockbots %}  <meta name="robots" content="NONE,NOARCHIVE" />{% endblock %}

  <link rel="shortcut icon" href="favicon.ico">
  <link rel="apple-touch-icon" href="apple-touch-icon.png">
  <link href='https://fonts.googleapis.com/css?family=Work+Sans:400,100,300,200,500,600,700,800,900' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Libre+Baskerville:400,400italic,700' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" type="text/css" href="{% static "circly/css/bootstrap.css" %}" />
  <link rel="stylesheet" type="text/css" href="{% static "circly/css/style.css" %}" />
{% block stylesheets %}{% endblock %}

  <script src="{% static "circly/js/modernizr.min.js" %}" ></script>
  <script type="text/javascript">
    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-XXXXXXXX-X']);
    _gaq.push(['_trackPageview']);
    (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();
  </script>

{% block headscripts %}{% endblock %}
</head>
<body{% block bodyattrs %}{% endblock %}>

{% block contentdivstart %}{% endblock %}

<header>
  <div class="container">
    <h1><a href="{% url 'connect:index' %}"><img src="{% static "circly/img/logo2.svg" %}" /></a></h1>
    <nav>
      <ul>
{% block nav %}
        <!-- <li><a href="">About</a></li> -->
        <li><a href="{% url 'connect:checkmeout' %}">#CheckMeOut</a></li>
        <li><a href="#signup">Sign Up</a></li>
{% endblock %}
      </ul>
    </nav>
  </div><!--/container-->
</header>

{% block contentdivfinish %}{% endblock %}

</div><!--/home-->

<footer>
  <div class="container">
    <p>Circly.org was built by <a href="https://twitter.com/mik3cap">Mike Caprio</a>, <a href="https://twitter.com/madelenamak">Madelena Mak</a>, <a href="https://twitter.com/kennedysgarage">Kennedy</a>, and <a href="https://twitter.com/spelsasaurus">Sarah Pels</a> at the 2015 <a href="http://codersvscancer.splashthat.com/">Coders vs. Cancer</a> hackathon. <a href="https://github.com/mik3cap/serkli">View Source Code</a>.</p>
  </div><!--/container-->
</footer>

<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script>window.jQuery || document.write('<script src="{% static "circly/js/jquery-1.11.3.min.js" %}" ><\/script>')</script>
<script src="{% static "circly/js/script.js" %}" ></script>
{% block bodyscripts %}{% endblock %}
</body>
</html>

event_meet/templates/circly/checkmeout.html
{% extends "circly/base.html" %}
{% load static from staticfiles %}
{% block title %}#CheckMeOut | Circly{% endblock %}

{% block contentdivstart %}<div id="checkmeout">{% endblock %}

{% block contentdivfinish %}
  <section class="intro">
    <div class="container">
      <h1>Check mine, now check yours.</h1>
      <img src="{% static "circly/img/nips.svg" %}" />
    </div><!--/container-->
  </section>

  <section>
    <div class="container">

      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <div class="title">
            <h3>#CheckMeOut</h3>
            <hr/>
            <p>Men, help the ladies in your life. They have always been their for you, it’s time that you are there for them.</p>
          </div><!--/title-->
        </div><!--/col-->
      </div><!--/row-->

      <div class="row">
        <div class="col-md-4 col-md-offset-1">
          <img src="{% static "circly/img/phone.png" %}" />
        </div><!--/col-->
        <div class="col-md-5">
          <ul class="steps">
            <li>
              <img src="{% static "circly/img/1.svg" %}" />
              <span>Snap a pick of your man boob.</span>
            </li>
            <li>
              <img src="{% static "circly/img/2.svg" %}" />
              <span>Send a message reminding your loved one to self examine their breasts.</span>
            </li>
            <li>
              <img src="{% static "circly/img/3.svg" %}" />
              <span>Sit back knowing that you reached out, made them smile, and helped them take care of themselves.</span>
            </li>
          </ul>
        </div><!--/col-->
      </div><!--/row-->

    </div><!--/container-->

  </section>

  <div class="separator"><hr /></div>

  <section class="nippics clearfix">
    <div class="container">

      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <div class="title">
            <h3>Get Social</h3>
            <hr/>
            <p>Join over 2,000+ men that care about the women in their lives. Some are daring enough to expose theirself to the world.</p>
          </div><!--/title-->
        </div><!--/col-->
      </div><!--/row-->
    </div><!--/container-->

    <ul class="nips">
      <li><a href="https://instagram.com/p/7g2fkRgRUr/?taken-by=kennedysgarage"><img src="{% static "circly/img/nips/1.png" %}" /></a></li>
      <li><img src="{% static "circly/img/nips/2.png" %}" /></li>
      <li><img src="{% static "circly/img/nips/3.png" %}" /></li>
      <li><img src="{% static "circly/img/nips/4.png" %}" /></li>
      <li><img src="{% static "circly/img/nips/5.png" %}" /></li>
      <li><img src="{% static "circly/img/nips/6.png" %}" /></li>
      <li><img src="{% static "circly/img/nips/7.png" %}" /></li>
      <li><img src="{% static "circly/img/nips/8.png" %}" /></li>
      <li><img src="{% static "circly/img/nips/9.png" %}" /></li>
      <li><img src="{% static "circly/img/nips/10.png" %}" /></li>
      <li><img src="{% static "circly/img/nips/11.png" %}" /></li>
      <li><img src="{% static "circly/img/nips/12.png" %}" /></li>
      <li><img src="{% static "circly/img/nips/13.png" %}" /></li>
      <li><img src="{% static "circly/img/nips/14.png" %}" /></li>
      <li><img src="{% static "circly/img/nips/15.png" %}"  /></li>
    </ul>

  </section>
{% endblock %}

event_meet/templates/circly/index.html
{% extends "circly/base.html" %}
{% load static from staticfiles %}
{% block title %}Circly{% endblock %}

{% block bodyattrs %} onload="goToOnLoadAnchor"{% endblock %}

{% block contentdivstart %}<div id="home">{% endblock %}

{% block contentdivfinish %}
<section class="intro">
  <div class="container">
    <div class="row">
      <div class="col-md-10 col-md-offset-1">
        <h1>Self care through the healing power of your circle.</h1>
        <h2>1 in 8 women will develop breast cancer‎. Circly can help you, your friends, and your family lower your risk of breast cancer. Just tell us a little about yourself so we can help you understand what your risks are.</h2>

        <a href="#signup" class="btn btn-default btn-lg ghost">Get Started</a>
      </div>
    </div>
  </div>
</section>

<section class="features">
  <div class="container">
    <div class="row">
      <ul>
        <li class="col-md-4">
          <img src="{% static "circly/img/care.svg" %}" />
          <h3>Preventive Care</h3>
          <p>There are many positive steps we can all take to prevent breast cancer. The research has been done; you can easily learn about the risks and stay healthy by staying connected.</p>
        </li>
        <li class="col-md-4">
          <img src="{% static "circly/img/network.svg" %}" />
          <h3>Use Your Network</h3>
          <p>You are extremely likely to know people who have been affected by breast cancer, either through their own diagnosis or the experience of a family member.</p>
        </li>
        <li class="col-md-4">
          <img src="{% static "circly/img/safe.svg" %}" />
          <h3>Safe &amp; Secure</h3>
          <p>We have built a system that gives you a safe, simple, and secure way to connect and stay connected with your friends and family.</p>
        </li>
      </ul>
    </div>
  </div>
</section>

<section class="network">
  <div class="container">
    <h3>You are not alone.</h3>
  </div>
</section>

<a name="signup"></a>
<section class="getstarted">
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <div class="title">
          <h3>Get Started</h3>
          <hr/>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-10 col-md-offset-1">
        {{ custom_errors }}

        <form class="madlib" action="{% url 'connect:submitname' %}" method="post">
          {% csrf_token %}
          <p>My <label for="first_name">name</label> is <input type="text" id="first_name" name="first_name" value="{{ first_name }}">, my <label for="contact_info">contact info</label> is <input type="text" id="contact_info" name="contact_info" placeholder="Email or Cell" value="{{ contact_info }}">, and I want to create a circle of support to prevent breast cancer.</p>
          <input type="submit" class="btn btn-primary btn-lg" value="Sign Up" />
        </form>
      </div>
    </div>
  </div>
</section>
{% endblock %}

{% block bodyscripts %}
<script>
  function goToOnLoadAnchor()
  {
      window.location.hash('{{ anchor }}');
  }
</script>
{% endblock %}

event_meet/templates/circly/network.html
{% extends "circly/base.html" %}
{% load static from staticfiles %}
{% block title %}Dashboard | Circly{% endblock %}

{% block contentdivstart %}<div id="network">{% endblock %}

{% block contentdivfinish %}
<section>
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <div class="title">
          <h3>Add your loved ones</h3>
          <hr/>
          <p>Choose at least three more people whom you know will support you, that you will take care of in turn.</p>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-8 col-md-offset-2">
        {{ custom_errors }}

        <form class="form-horizontal" action="{% url 'connect:submitcircle' %}" method="post">
          {% csrf_token %}

          {% for i in num_range_str %}
          <div class="row">
            <div class="col-md-6">
              <div class="form-group">
                <label for="name_{{ i }}" class="col-sm-4 control-label">Member #{{ i }}</label>
                <div class="col-sm-8">
                  <input type="text" class="form-control" id="name_{{ i }}" name="name_{{ i }}" placeholder="Name">
                </div>
              </div>
            </div>
            <div class="col-md-6">
              <div class="form-group">
                <label for="contact_{{ i }}" class="col-sm-4 control-label">Contact</label>
                <div class="col-sm-8">
                  <input type="text" class="form-control" id="contact_{{ i }}" name="contact_{{ i }}" placeholder="Email or Mobile Phone">
                </div>
              </div>
            </div>
          </div>
          {% endfor %}

          <div class="row">
            <div class="col-md-6 col-md-offset-5">
              <div class="title"></div>
              <input type="submit" class="btn btn-primary btn-lg" value="Next" />
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</section>
{% endblock %}

event_meet/templates/circly/profile_form_snippet.html
          {% csrf_token %}

          <p>I am a {{ form.chromosome }} who is {{ form.age }} years old and my <label for="{{ form.ethnicity.id_for_label }}">ethnicity</label> is {{ form.ethnicity }}. I {{ form.drink }} <label for="{{ form.bmi.id_for_label }}">drink</label>, {{ form.smoke }} <label for="{{ form.smoke.id_for_label }}">smoke</label>, and {{ form.exercise }} <label for="{{ form.exercise.id_for_label }}">exercise</label>. My <label for="{{ form.bmi.id_for_label }}">BMI</label> is {{ form.bmi }}. I have {{ form.relatives }} <label for="{{ form.relatives.id_for_label }}">immediate relatives</label> (mother, daughter, sibling) diagnosed with breast cancer.</p>
          {{ form.invite }}
          <input type="submit" class="btn btn-primary btn-lg" value="Next" />